name: Deploy Plugin

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-18.04
    name: Test Assets
    steps:
      - uses: actions/checkout@master

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Install NPM Packages
        run: npm install

      - name: Check JS & CSS syntax
        run: npm test

  deploy:
    runs-on: ubuntu-18.04
    name: Deploy to Production
    needs: test
    steps:
      - uses: actions/checkout@master

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Install NPM Packages
        run: npm install

      - name: Build Docs
        run: npm run build

      - name: Copy Original Files
        run: cp docs-prevent/* docs/

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'docs'
          destination-github-username: 'dead-channel-jp'
          destination-repository-name: 'dead-channel-jp.github.io'
          user-email: guy@hametuha.com
          target-branch: master

